import test,{before,beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {decodeResearchBatch} from '../src/domain/researchBatch.ts';
import {editorialAssessment,filterEditorial,approvalEffect} from '../src/domain/editorial.ts';
import {prepareResearchImport} from '../scripts/prepare-research-import.mjs';
const editor='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const stamp='2026-10-11T00:00:00Z';
const candidate=(suffix='one')=>({researchId:`test-${suffix}`,name:`架空の居酒屋 ${suffix}`,address:`名古屋市中区1番地 ${suffix}`,area:'栄',cuisine:'居酒屋',officialUrl:'https://example.test/store',facts:[{field:'name',value:`架空の居酒屋 ${suffix}`},{field:'address',value:`名古屋市中区1番地 ${suffix}`},{field:'website',value:'https://example.test/store'},{field:'genre',value:'居酒屋'}].map(f=>({...f,sourceUrl:'https://example.test/store',checkedAt:stamp,sourceType:'official',confidence:'confirmed'})),unknowns:['個室の遮音性'],ownerDecision:'普段の会食候補として掲載するか。',researchNotes:'テスト専用の架空情報。'});
const batch=(values=[candidate()])=>({schemaVersion:1,batchId:'test-batch',researchedAt:stamp,candidates:values});
let db;
async function identity(id,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id??'']);await db.exec(`set role ${role}`);}
async function rpc(name,args=[]){return(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;}
before(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;grant usage on schema auth to public;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;`);await db.exec(await readFile(new URL('../supabase/migrations/202610050001_nagoya_foundation.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/proposals/202610050002_catalog_source_eligibility.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/proposals/20261011010120_editorial_operations.sql',import.meta.url),'utf8'));await db.query('insert into auth.users values($1),($2)',[editor,other]);await db.query('insert into dining_private.editors(user_id) values($1)',[editor]);});
beforeEach(async()=>{await db.exec('reset role;truncate dining_private.restaurants,dining_private.moderation_events cascade;update dining_private.settings set public_enabled=false,reviews_enabled=false;');});after(async()=>db.close());
test('strict research schema preserves unresolved addresses and rejects duplicates, false URLs and mismatched identities',()=>{const c=candidate();c.facts.find(f=>f.field==='address').confidence='unconfirmed';assert.equal(decodeResearchBatch(batch([c])).candidates[0].facts[1].confidence,'unconfirmed');assert.throws(()=>decodeResearchBatch(batch([c,c])));assert.throws(()=>decodeResearchBatch(batch([{...c,officialUrl:'javascript:alert(1)'}])));const changed=candidate();changed.facts[0].value='different shop';assert.throws(()=>decodeResearchBatch(batch([changed])));});
test('new APIs deny anonymous and signed-in non-editors without modifying roles or tables',async()=>{for(const [actor,role] of [[null,'anon'],[other,'authenticated']]){await identity(actor,role);await assert.rejects(rpc('dining_editor_context'));await assert.rejects(rpc('dining_create_candidate',['Test','名古屋市中区','https://example.test',randomUUID()]));}await identity(editor);const c=await rpc('dining_editor_context');assert.equal(c.publicEnabled,false);assert.equal(c.manualIntakeEnabled,true);await assert.rejects(db.query('select * from dining_private.restaurants'),/permission denied/);});
test('manual intake is real, candidate-only, idempotent and rejects changed request payload or duplicate store',async()=>{await identity(editor);const id=randomUUID();const args=['架空店舗','名古屋市中区1','https://example.test',id];const a=await rpc('dining_create_candidate',args);const b=await rpc('dining_create_candidate',args);assert.equal(a.id,b.id);assert.equal(b.replayed,true);await assert.rejects(rpc('dining_create_candidate',['別店舗',...args.slice(1)]),/different input/);await assert.rejects(rpc('dining_create_candidate',[...args.slice(0,3),randomUUID()]),/already exists/);await assert.rejects(rpc('dining_create_candidate',['Null','名古屋市中区',null,randomUUID()]));assert.deepEqual(await rpc('dining_public_catalog'),[]);await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from dining_private.moderation_events')).rows[0].n,1);assert.equal((await db.query('select count(*)::int n from dining_private.restaurant_facts')).rows[0].n,0);});
test('manual intake respects daily and total caps without receipts or data growth from failed attempts',async()=>{await identity(editor);for(let i=0;i<10;i++)await rpc('dining_create_candidate',[`店${i}`,`名古屋市中区${i}`,'https://example.test',randomUUID()]);await assert.rejects(rpc('dining_create_candidate',['店11','名古屋市中区11','https://example.test',randomUUID()]),/Daily/);await db.exec("reset role;insert into dining_private.restaurants(candidate_name,candidate_address,city) select '追加'||g,'名古屋市'||g,'名古屋市' from generate_series(1,190) g");await identity(editor);await assert.rejects(rpc('dining_create_candidate',['店201','名古屋市中区201','https://example.test',randomUUID()]),/queue limit/);});
test('100 research candidates import once, retain unconfirmed fields privately, and never publish or change trial targets',async()=>{const data=batch(Array.from({length:100},(_,i)=>candidate(`store-${i}`)));data.candidates[3].facts[1].confidence='unconfirmed';const sql=prepareResearchImport(data);await db.exec(sql);await db.exec(sql);const rows=(await db.query('select count(*)::int n from dining_private.restaurants')).rows[0];assert.equal(rows.n,100);assert.equal((await db.query('select count(*)::int n from dining_private.restaurant_facts')).rows[0].n,399);assert.equal((await db.query('select max(version)::int v from dining_private.restaurants')).rows[0].v,2);await identity(editor);const queue=await rpc('dining_editor_queue');assert.equal(queue.length,100);const unknown=queue.find(r=>r.name.endsWith('store-3'));assert.equal(editorialAssessment(unknown).ready,false);assert.equal(filterEditorial(queue,'居酒屋','ready','').length,99);assert.deepEqual(await rpc('dining_public_catalog'),[]);});
test('import protects existing facts, uses SQL-safe literals and rejects altered replays atomically',async()=>{const data=batch();data.candidates[0].ownerDecision="Judge $$ '; select 'injection'; --";await db.exec(prepareResearchImport(data));await db.exec("update dining_private.restaurant_facts set value='User correction' where field='genre'");await db.exec(prepareResearchImport(data));assert.equal((await db.query("select value from dining_private.restaurant_facts where field='genre'")).rows[0].value,'User correction');data.candidates[0].ownerDecision='Changed';await assert.rejects(db.exec(prepareResearchImport(data)),/batch changed/);await db.exec('rollback');});
test('approval checks the displayed publication state atomically and still requires official core facts',async()=>{await db.exec(prepareResearchImport(batch()));await identity(editor);const row=(await rpc('dining_editor_queue'))[0];assert.match(approvalEffect({...row,publicEnabled:false}),/一般公開は停止中/);await rpc('dining_save_listing_decision',[row.id,row.version,'verified','会食候補として掲載',false]);assert.deepEqual(await rpc('dining_public_catalog'),[]);await db.exec('reset role;update dining_private.settings set public_enabled=true');await identity(editor);await assert.rejects(rpc('dining_save_listing_decision',[row.id,row.version+1,'candidate','再確認',false]),/Publication setting changed/);await assert.rejects(rpc('dining_save_listing_decision',[row.id,row.version+1,'candidate','再確認',null]),/Publication setting changed/);assert.equal((await rpc('dining_editor_queue'))[0].status,'verified');});
test('exact batch replay never restores removed facts or silently changes an optimistic version',async()=>{const sql=prepareResearchImport(batch());await db.exec(sql);await db.exec("delete from dining_private.restaurant_facts where field='genre'");await db.exec(sql);assert.equal((await db.query("select count(*)::int n from dining_private.restaurant_facts where field='genre'")).rows[0].n,0);assert.equal((await db.query('select version from dining_private.restaurants')).rows[0].version,2);const next={...batch(),batchId:'test-batch-recheck'};await db.exec(prepareResearchImport(next));assert.equal((await db.query("select count(*)::int n from dining_private.restaurant_facts where field='genre'")).rows[0].n,1);assert.equal((await db.query('select version from dining_private.restaurants')).rows[0].version,3);});
test('existing mapping is one-to-one and requires the exact existing name and address',async()=>{const c=candidate(),id=randomUUID();const mapping={researchId:c.researchId,id,name:c.name,address:c.address};assert.throws(()=>prepareResearchImport(batch([c,candidate('two')]),[mapping,{...mapping,researchId:'test-two'}]),/mapping/);assert.throws(()=>prepareResearchImport(batch(),[{...mapping,address:undefined}]),/mapping/);assert.throws(()=>prepareResearchImport(batch(),[{...mapping,name:'違う店名'}]),/name differs/);await db.query('insert into dining_private.restaurants(id,candidate_name,candidate_address,city) values($1,$2,$3,$4)',[id,c.name,'名古屋市 違う住所','名古屋市']);await assert.rejects(db.exec(prepareResearchImport(batch(),[mapping])),/mapping changed/);await db.exec('rollback');assert.equal((await db.query('select count(*)::int n from dining_private.restaurant_sources')).rows[0].n,0);});
test('legacy moderation cannot bypass the checked publication effect',async()=>{await db.exec(prepareResearchImport(batch()));await identity(editor);const row=(await rpc('dining_editor_queue'))[0];await assert.rejects(rpc('dining_moderate_restaurant',[row.id,row.version,'verified','掲載候補']),/permission denied/);await rpc('dining_save_listing_decision',[row.id,row.version,'verified','掲載候補',false]);assert.equal((await rpc('dining_editor_queue'))[0].status,'verified');});
