import { useEffect, useMemo, useRef, useState } from 'react';
import EditorialPreview from '../components/CatalogPresentation';
import { useAppAccess } from '../contexts/appAccess';
import { useAuth } from '../contexts/auth';
import { emailSignInEnabled, googleSignInEnabled } from '../lib/supabase';
import { diningRepository } from '../data/diningClient';
import type { EditorialContext } from '../data/repositories/diningRepository';
import { FACT_LABELS, factValue, safeExternalUrl, type EditorialRestaurant, type FactField, type VerificationStatus } from '../domain/dining';
import { approvalEffect, editorialAssessment, EDITORIAL_STATUS, filterEditorial } from '../domain/editorial';
const date=(value:string)=>new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',dateStyle:'medium'}).format(new Date(value));
type EditDraft={reason:string;field:FactField;value:string;url:string;checked:boolean};
const emptyDraft=():EditDraft=>({reason:'',field:'name',value:'',url:'',checked:false});
function CandidateEditor({row,draft,onDraft,reload,onBack}:{row:EditorialRestaurant;draft:EditDraft;onDraft:(draft:EditDraft)=>void;reload:()=>Promise<void>;onBack:()=>void}){
 const assessment=editorialAssessment(row);const mapsUrl=new URL('https://www.google.com/maps/search/');mapsUrl.searchParams.set('api','1');mapsUrl.searchParams.set('query',`${row.name} ${row.address}`);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [confirm,setConfirm]=useState<VerificationStatus|null>(null);const guard=useRef(false);
 const update=(values:Partial<EditDraft>)=>onDraft({...draft,...values});
 const execute=async(action:()=>Promise<void>,success:string)=>{if(guard.current)return;guard.current=true;setBusy(true);setError('');setMessage('');let accepted=false;try{await action();accepted=true;await reload();onDraft(emptyDraft());setMessage(success);}catch{setError(accepted?'保存は受け付けられました。一覧を再読み込みして最新の状態を確認してください。':'保存結果を確認できません。重複して送らず、一覧を再読み込みして権限と最新の状態を確認してください。');}finally{guard.current=false;setBusy(false);setConfirm(null);}};
 const chooseField=(field:FactField)=>{const existing=row.facts.find(f=>f.field===field);const researched=assessment.research?.facts.find(f=>f.field===field&&f.sourceType==='official');update({field,value:existing?.value??researched?.value??'',url:existing?.sourceUrl??researched?.sourceUrl??'',checked:false});};
 return <article className="editorial-detail" tabIndex={-1} aria-label={`${row.name}の確認・判断`}>
  <button className="catalog-reset editorial-back" onClick={onBack}>店舗一覧に戻る</button>
  <div className="editorial-detail-title"><p className="eyebrow">{EDITORIAL_STATUS[row.status]} · {assessment.cuisine}</p><h2>{row.name}</h2><p>{row.address}</p><p className="editorial-state">次にすること：{assessment.nextAction}</p></div>
  <section className="editorial-section"><h3>1. こちらで調べた事実</h3><p className="quiet-label">公式情報の確認記録です。来店による評価ではありません。</p>{row.facts.length?<dl className="editorial-facts">{row.facts.map(fact=><div key={fact.field}><dt>{FACT_LABELS[fact.field]}</dt><dd><p>{fact.value}</p><a href={safeExternalUrl(fact.sourceUrl)??undefined} target="_blank" rel="noreferrer">{FACT_LABELS[fact.field]}の出典</a><span className="quiet-label"> · 確認 {date(fact.verifiedAt)}</span></dd></div>)}</dl>:<p>公式の確認記録はまだありません。下の調査資料から内容を確認できます。</p>}
   {assessment.research?.facts.some(f=>!row.facts.some(saved=>saved.field===f.field))&&<details><summary>未保存の調査メモを見る</summary>{assessment.research.facts.filter(f=>!row.facts.some(saved=>saved.field===f.field)).map(f=><p key={f.field}><strong>{FACT_LABELS[f.field]}</strong>：{f.value} <a href={f.sourceUrl} target="_blank" rel="noreferrer">出典</a>（{f.sourceType==='official'?'公式資料':'外部資料'}・{f.confidence==='confirmed'?'資料確認済み':'未確認'}）</p>)}</details>}
  </section>
  <section className="editorial-section editorial-unknown"><h3>2. まだ分からないこと</h3>{assessment.missingCore.length>0&&<p className="form-error">承認に必要な基本情報：{assessment.missingCore.map(f=>FACT_LABELS[f]).join('・')}</p>}<ul>{assessment.unknowns.map((item,i)=><li key={i}>{item}</li>)}<li>実際の静かさ・接客・空席は、公式情報だけでは判断していません。</li></ul><p className="quiet-label">Googleの評価・評価件数は未取得です。必要な場合は参考情報として別画面で確認できます。</p><a className="button-secondary" href={mapsUrl.href} target="_blank" rel="noreferrer">Googleマップで評価を見る（外部）</a></section>
  <section className="editorial-section editorial-decision"><h3>3. あなたに決めてほしいこと</h3><p className="editorial-question">{assessment.decision}</p><p>高級店に限りません。居酒屋・焼鳥も、普段の会食候補として選べます。未確認の条件は、未確認のまま掲載します。</p><EditorialPreview restaurant={row}/><label>審査理由<textarea required maxLength={1000} value={draft.reason} onChange={e=>update({reason:e.target.value})} placeholder="例：名駅で普段の会食に使う候補。個室条件は予約前に要確認。" /></label>
   <div className="editorial-effect"><strong>承認すると</strong><p>{approvalEffect(row)}</p><p>承認は店舗情報への判断です。写真の転載許可、口コミの承認、サイトの一般公開設定は変更しません。</p></div>
   <div className="curation-actions"><button className="primary-button" disabled={busy||!draft.reason.trim()||row.status==='verified'||!assessment.ready||assessment.publicEnabled===null} onClick={()=>setConfirm('verified')}>掲載候補として承認</button><button className="button-secondary" disabled={busy||!draft.reason.trim()||row.status==='candidate'||assessment.publicEnabled===null} onClick={()=>setConfirm('candidate')}>判断待ちに戻す</button><button className="button-secondary" disabled={busy||!draft.reason.trim()||row.status==='rejected'||assessment.publicEnabled===null} onClick={()=>setConfirm('rejected')}>対象外にする</button></div>
   {confirm&&<div className="curation-confirm" role="region" aria-label="掲載判断の確認"><p>「{row.name}」を「{EDITORIAL_STATUS[confirm]}」に変更します。</p><p>{confirm==='verified'?approvalEffect(row):'公開中であれば、公開一覧から外れます。記録は削除しません。'}</p><p>理由：{draft.reason}</p><div className="curation-actions"><button className="button-secondary" disabled={busy} onClick={()=>void execute(()=>diningRepository!.moderate(row.id,row.version,confirm,draft.reason,assessment.publicEnabled!),'掲載判断を保存しました。')}>判断を確定する</button><button className="catalog-reset" disabled={busy} onClick={()=>setConfirm(null)}>キャンセル</button></div></div>}
  </section>
  <section className="editorial-section"><h3>4. 情報を修正・追加する</h3><details><summary>公式情報を確認して記録する</summary><p>保存すると承認済みでも判断待ちに戻ります。現在の記録を読み込んで修正できます。</p><form onSubmit={e=>{e.preventDefault();if(draft.checked)void execute(()=>diningRepository!.recordFact(row.id,row.version,draft.field,draft.value,draft.url),'確認記録を保存しました。掲載判断をもう一度行ってください。');}}><label>確認項目<select aria-label="確認項目" value={draft.field} onChange={e=>chooseField(e.target.value as FactField)}>{Object.entries(FACT_LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button type="button" className="catalog-reset" onClick={()=>chooseField(draft.field)}>現在の記録を読み込む</button><label>確認した内容<textarea required maxLength={1500} value={draft.value} onChange={e=>update({value:e.target.value,checked:false})} placeholder={draft.field==='coordinates'?'経度,緯度（店舗単位の位置を確認した場合のみ）':'確認できた事実を短く記録'} /></label><label>公式ページのURL<input type="url" required pattern="https://.*" value={draft.url} onChange={e=>update({url:e.target.value,checked:false})}/></label><label className="draft-check"><input type="checkbox" checked={draft.checked} onChange={e=>update({checked:e.target.checked})}/>公式ページを開き、入力した内容と利用条件を確認しました</label><button className="button-secondary" disabled={busy||!draft.checked}>確認記録を保存</button></form></details></section>
  <details className="editorial-source-details"><summary>取得元・利用条件（{row.sources.length}件）</summary><ul>{row.sources.map(source=><li key={source.id}>{source.provider} · {safeExternalUrl(source.sourceUrl)&&<a href={safeExternalUrl(source.sourceUrl)!} target="_blank" rel="noreferrer">出典を開く</a>}<br/>取得 {date(source.fetchedAt)} / 確認 {source.verifiedAt?date(source.verifiedAt):'未確認'}<br/>利用根拠：{source.publicationBasis} · ライセンス：{source.licenses.join(', ')||'未記載'}<br/>{source.attributions.join(' / ')}{source.rawRecord&&<details><summary>取得時の資料を見る</summary><pre className="source-snapshot">{JSON.stringify(source.rawRecord,null,2)}</pre></details>}</li>)}</ul></details>
  {error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status" className="sample-notice">{message}</p>}
 </article>;
}
function CandidateIntake({enabled,onCreated}:{enabled:boolean;onCreated:(id:string)=>Promise<void>}){
 const [name,setName]=useState('');const [address,setAddress]=useState('');const [website,setWebsite]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const request=useRef<string|null>(null);const guard=useRef(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!enabled||guard.current)return;guard.current=true;setBusy(true);setError('');setMessage('');request.current??=crypto.randomUUID();try{const id=await diningRepository!.createCandidate(name,address,website,request.current);await onCreated(id);setName('');setAddress('');setWebsite('');request.current=null;setMessage('候補を追加しました。公式の調査記録を追加してから掲載判断へ進めます。');}catch{setError('追加結果を確認できません。同じ内容のまま一覧を再読み込みして確認してください。入力内容は保持しています。');}finally{guard.current=false;setBusy(false);}};
 return <details className="editorial-intake"><summary>店舗候補を1件追加する</summary><p>店舗を登録しても公開されません。公式情報の調査・あなたの掲載判断を経て承認します。</p>{!enabled?<p>候補追加APIの適用を待っています。現在は追加できません。</p>:<form onSubmit={e=>void submit(e)}><label>店舗名<input required maxLength={200} value={name} onChange={e=>{setName(e.target.value);request.current=null;}} disabled={busy}/></label><label>所在地<input required maxLength={500} value={address} onChange={e=>{setAddress(e.target.value);request.current=null;}} placeholder="名古屋市から入力" disabled={busy}/></label><label>公式サイト<input required type="url" pattern="https://.*" maxLength={2000} value={website} onChange={e=>{setWebsite(e.target.value);request.current=null;}} disabled={busy}/></label><button className="button-secondary" disabled={busy}>候補として追加</button></form>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</details>;
}
function EditorWorkspace(){
 const [state,setState]=useState<'loading'|'denied'|'ready'|'error'>('loading');const [rows,setRows]=useState<EditorialRestaurant[]>([]);const [context,setContext]=useState<EditorialContext|null>(null);const [revision,setRevision]=useState(0);const [query,setQuery]=useState('');const [stage,setStage]=useState('');const [cuisine,setCuisine]=useState('');const [selected,setSelected]=useState('');const [page,setPage]=useState(0);const [drafts,setDrafts]=useState<Record<string,EditDraft>>({});const alive=useRef(true);
 useEffect(()=>{alive.current=true;const controller=new AbortController();void(async()=>{try{if(await diningRepository!.canEdit(controller.signal)!==true){if(!controller.signal.aborted)setState('denied');return;}const [queue,config]=await Promise.all([diningRepository!.listEditorial(controller.signal),diningRepository!.editorContext(controller.signal).catch(()=>null)]);if(!controller.signal.aborted){setRows(queue);setContext(config);setState('ready');}}catch{if(!controller.signal.aborted)setState('error');}})();return()=>{alive.current=false;controller.abort();};},[revision]);
 useEffect(()=>{if(selected){const panel=document.querySelector<HTMLElement>('.editorial-detail');panel?.focus({preventScroll:true});if(window.matchMedia('(max-width:800px)').matches)panel?.scrollIntoView({block:'start'});}},[selected]);
 const reload=async()=>{const [queue,config]=await Promise.all([diningRepository!.listEditorial(),diningRepository!.editorContext().catch(()=>null)]);if(alive.current){setRows(queue);setContext(config);}};
 const enriched=useMemo(()=>rows.map(row=>({...row,publicEnabled:context?.publicEnabled})),[rows,context]);
 const filtered=useMemo(()=>filterEditorial(enriched,query,stage,cuisine),[enriched,query,stage,cuisine]);const pages=Math.max(1,Math.ceil(filtered.length/20));const currentPage=Math.min(page,pages-1);const shown=filtered.slice(currentPage*20,currentPage*20+20);const active=enriched.find(row=>row.id===selected);const cuisines=[...new Set(enriched.map(row=>editorialAssessment(row).cuisine))].sort();
 const ready=rows.filter(row=>row.status==='candidate'&&editorialAssessment(row).ready).length;const research=rows.filter(row=>row.status==='candidate'&&!editorialAssessment(row).ready).length;
 if(state==='loading')return <p role="status">編集権限と店舗情報を確認しています…</p>;
 if(state==='denied')return <div className="catalog-empty"><h2>編集権限が必要です</h2><p>このアカウントには運営者としての権限がありません。</p></div>;
 if(state==='error')return <div className="catalog-empty" role="alert"><h2>審査用の情報を読み込めませんでした</h2><button className="button-secondary" onClick={()=>{setState('loading');setRevision(n=>n+1);}}>再読み込み</button></div>;
 return <>
  <section className="editorial-overview" aria-label="店舗運営の進捗"><div><span>登録候補</span><strong>{rows.length}</strong></div><div><span>あなたの判断待ち</span><strong>{ready}</strong></div><div><span>基本情報の調査待ち</span><strong>{research}</strong></div><div><span>承認済み</span><strong>{rows.filter(row=>row.status==='verified').length}</strong></div></section>
  <div className="editorial-public-state"><strong>{context?(context.publicEnabled?'一般公開：有効':'一般公開：停止中'):'公開設定：取得待ち'}</strong><p>{context?.publicEnabled===false?'承認操作は店の状態だけを保存します。一般公開の開始は別の操作です。':context?.publicEnabled===true?'承認すると、確認済み情報が公開一覧へ反映されます。':'店舗情報は読めますが、承認後の公開範囲を確認できるまで承認ボタンは使えません。'}</p><button className="catalog-reset" onClick={()=>{setState('loading');setRevision(n=>n+1);}}>一覧を再読み込み</button></div>
  <details className="editorial-workflow"><summary>店舗を追加してから公開するまで</summary><ol><li><strong>候補を追加</strong>：下のフォーム、または調査した候補一覧を取り込みます。</li><li><strong>こちらで調査</strong>：店名・所在地・料理・料金・個室などを公式情報から整理し、出典と未確認事項を残します。</li><li><strong>あなたが判断</strong>：1店ずつ、普段の会食候補として掲載するか理由を添えて決めます。高級店だけに限定しません。</li><li><strong>承認を保存</strong>：店舗が承認済みになります。公開設定が停止中なら一般公開されません。</li><li><strong>反映・修正</strong>：公開設定が有効なときに承認済み情報が反映されます。事実の修正後は再び判断待ちになります。</li></ol><p>一般公開、会員募集、実口コミの受付はそれぞれ別の設定です。この画面から一括で開始しません。</p></details>
  <CandidateIntake enabled={context?.manualIntakeEnabled===true} onCreated={async id=>{await reload();setQuery('');setStage('');setCuisine('');setPage(0);setSelected(id);}}/>
  <div className="editorial-filters"><label>店舗名・地域<input aria-label="管理する店舗を検索" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);setSelected('');}} placeholder="名駅・焼鳥・店名など"/></label><label>対応状況<select aria-label="対応状況" value={stage} onChange={e=>{setStage(e.target.value);setPage(0);setSelected('');}}><option value="">すべて</option><option value="ready">あなたの判断待ち</option><option value="research">基本情報の調査待ち</option><option value="verified">承認済み</option><option value="rejected">対象外</option></select></label><label>料理<select aria-label="管理する料理" value={cuisine} onChange={e=>{setCuisine(e.target.value);setPage(0);setSelected('');}}><option value="">すべて</option>{cuisines.map(c=><option key={c}>{c}</option>)}</select></label></div>
  <p className="catalog-count">登録 {rows.length}件 · 絞り込み {filtered.length}件</p>
  <div className={`editorial-board${active?' has-selection':''}`}><section className="editorial-list" aria-label="確認する店舗一覧">{shown.map(row=>{const a=editorialAssessment(row);return <article className={`curation-card editorial-list-card${row.id===selected?' is-selected':''}`} key={row.id}><button onClick={()=>setSelected(row.id)} aria-label={`${row.name}を確認する`} aria-pressed={row.id===selected}><span className="eyebrow">{a.nextAction} · {a.cuisine}</span><h2>{row.name}</h2><span>{row.address}</span><span className="editorial-price">{factValue(row,'price')??'料金は未確認'}</span><span className="editorial-record-count">公式記録 {row.facts.length}項目 · 未確認 {a.unknowns.length}項目</span></button></article>;})}{!filtered.length&&<div className="catalog-empty"><h2>{rows.length?'条件に合う候補はありません':'確認待ちの候補はありません'}</h2><p>候補の追加、または検索条件の変更で確認を進められます。</p></div>}<div className="editorial-pagination"><button className="button-secondary" disabled={currentPage===0} onClick={()=>setPage(n=>Math.max(0,n-1))}>前の20件</button><span>{currentPage+1} / {pages}</span><button className="button-secondary" disabled={currentPage>=pages-1} onClick={()=>setPage(n=>n+1)}>次の20件</button></div></section><section className="editorial-selected">{active?<CandidateEditor key={active.id} row={active} draft={drafts[active.id]??emptyDraft()} onDraft={draft=>setDrafts(values=>({...values,[active.id]:draft}))} reload={reload} onBack={()=>setSelected('')}/>:<div className="editorial-start"><h2>1店選んで、掲載判断へ。</h2><p>調査した事実と未確認事項を読み、会食候補として扱うか決めます。入力途中の判断メモは、この画面を開いている間は店舗を切り替えても残ります。</p></div>}</section></div>
 </>;
}
export default function Curation(){const {user,loading}=useAuth();const access=useAppAccess();return <div className="page-width catalog-page editorial-page"><div className="catalog-heading"><div><p className="eyebrow">EDITORIAL WORKSPACE</p><h1>店舗情報の確認・審査</h1><p>集めた候補を、会食に使える店舗一覧へ。</p>{access.ownerTrial&&access.editor&&<a className="button-secondary" href="#/pilot?view=queue">テスト投稿を確認</a>}</div></div>{!diningRepository?<div className="catalog-empty"><h2>管理機能は準備中です</h2><p>店舗データベースと編集権限の確認後に利用できます。</p></div>:loading?<p role="status">ログイン状態を確認しています…</p>:!user?<div className="catalog-empty"><h2>運営者のログインが必要です</h2><p>{googleSignInEnabled||emailSignInEnabled?'画面上部から、運営アカウントでログインしてください。':'ログイン設定の確認後に利用できます。'}</p></div>:<EditorWorkspace key={user.id}/>}</div>;}
