import { useState } from 'react';
import { COMPANY_SIZE_LABELS, INDUSTRY_LABELS, ROLE_LAYER_LABELS, MEMBERSHIP_COPY, publicProfileLabel, type PublicProfileChoice } from '../domain/membership';
import OperatorBadge from '../components/OperatorBadge';
const fixture: PublicProfileChoice = { industry: 'pharmaceutical', companySize: 'large', roleLayer: 'department', familyRomanization: 'Kensho', givenRomanization: 'Taro' };
export default function Membership() {
  const [step, setStep] = useState(1);
  const [choice, setChoice] = useState(fixture);
  const [consent, setConsent] = useState(false);
  const update = (key: 'industry' | 'companySize' | 'roleLayer', value: string) => { setChoice(current => ({ ...current, [key]: value })); setConsent(false); };
  return <div className="page-width catalog-page membership-page"><p className="eyebrow">MEMBERSHIP / DESIGN PREVIEW</p><h1>体験の背景が、ほどよく伝わる。</h1><p className="catalog-explainer">会員登録の操作デモです。すべて架空の情報で、実際の個人情報は入力できません。登録・送信・課金・特典付与は行いません。</p>
    <ol className="membership-steps" aria-label="登録画面の準備"><li aria-current={step === 1 ? 'step' : undefined}>1. 非公開の登録情報</li><li aria-current={step === 2 ? 'step' : undefined}>2. 公開表示を確認</li><li aria-current={step === 3 ? 'step' : undefined}>3. 会員機能</li></ol>
    {step === 1 && <section className="membership-card"><h2>まずは、登録情報を。</h2><p>会社名・氏名・正式な役職は一般公開しません。運営が扱う範囲・目的・削除方法の確定後に登録を開始します。</p><div className="membership-private-fixture" aria-label="架空の登録情報"><label>実会社名（非公開）<input readOnly value="デモ製薬株式会社（架空）" /></label><label>氏名（非公開）<input readOnly value="検証 太郎（架空）" /></label><label>正式な役職（非公開）<input readOnly value="営業企画部長（デモ）" /></label></div><p className="draft-privacy-note">この画面は保存しません。実際の登録では、非公開情報の保管と口コミへの公開表示を分けて確認します。</p><button className="primary-button" onClick={() => setStep(2)}>架空データで公開表示を試す</button></section>}
    {step === 2 && <section className="membership-card"><h2>口コミには、このように表示されます。</h2><div className="review-draft-grid"><label>業種（自己申告）<select aria-label="業種（自己申告）" value={choice.industry} onChange={event => update('industry', event.target.value)}>{Object.entries(INDUSTRY_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>会社規模（自己申告）<select aria-label="会社規模（自己申告）" value={choice.companySize} onChange={event => update('companySize', event.target.value)}>{Object.entries(COMPANY_SIZE_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><label>公開する役割の区分<select aria-label="公開する役割の区分" value={choice.roleLayer} onChange={event => update('roleLayer', event.target.value)}>{Object.entries(ROLE_LAYER_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><p className="draft-privacy-note">氏 Kensho → K、名 Taro → T の架空例です。実装時は本人が確認したローマ字を使い、読み方を推測しません。</p><div className="public-identity-preview" aria-label="公開ラベルの表示例"><strong>{publicProfileLabel(choice)}</strong><p>投稿時の所属区分・役割（自己申告）</p></div><p>会社名や氏名を隠しても、属性の組み合わせから本人が推測される場合があります。</p><label className="draft-check"><input type="checkbox" checked={consent} onChange={event => setConsent(event.target.checked)} />この公開表示を確認する（操作デモ）</label><div className="curation-actions"><button className="button-secondary" onClick={() => { setStep(1); setConsent(false); }}>登録情報の例へ戻る</button><button className="primary-button" disabled={!consent} onClick={() => setStep(3)}>会員機能の案を見る</button></div></section>}
    {step === 3 && <section className="membership-card"><h2>普段の利用も、初期の参加も。</h2><p>機能・特典の準備案です。いま会員権や永続特典が付与されるものではありません。</p><div className="membership-tiers">{(['member','plus','prime'] as const).map(key => <article key={key}><h3>{MEMBERSHIP_COPY[key].name}</h3><p>{MEMBERSHIP_COPY[key].description}</p></article>)}</div><p>本人の有益な体験投稿には、審査を経た期間付き機能開放も検討しています。有料プラン・称号・特典で口コミの評価や検索順位は変えません。</p><div className="operator-example"><p>運営表示の例</p><OperatorBadge badge="Owner" /><p>{MEMBERSHIP_COPY.owner.description} 実際の操作権限とは別に管理し、運営者が投稿する際はその関係を明示します。</p></div><button className="button-secondary" onClick={() => { setStep(2); setConsent(false); }}>公開表示を見直す</button><button className="button-secondary" disabled>会員登録は準備中</button></section>}
  </div>;
}
